vetmentor/urls.py
import os.path
from django.conf.urls import patterns, include
from mentor.views import contact, LandingView, SignupView, thanks
from django.contrib import admin

admin.autodiscover()

site_media = os.path.join(
    os.path.dirname(__file__),'site_media'
)

urlpatterns = patterns('',
    (r'^site_media/(?P<path>.*)$',
     'django.views.static.serve',{'document_root':site_media}),
    (r'^$', LandingView.as_view()),
    (r'^contact/$', contact),
    (r'^contact/thanks/$', thanks),
    (r'^signup$', SignupView.as_view()),
    #(r'^accounts/', include('allauth.urls')),
    (r'^admin/', include(admin.site.urls)),
)

vetmentor/mentor/models.py
from __future__ import unicode_literals

from datetime import datetime
from django.utils.timezone import utc
from django.contrib.auth.models import AbstractBaseUser
from django.db import models


class User(AbstractBaseUser):
    name = models.TextField()
    email = models.TextField(db_index=True) # unique
    birthday = models.DateField()
    MALE = 0
    FEMALE = 1
    GENDER_TYPES = (
        (MALE, 'male'),
        (FEMALE, 'female'),
    )
    gender = models.SmallIntegerField(choices=GENDER_TYPES)
    VETERAN = 0
    CIVILIAN = 1
    CATEGORY_TYPES = (
        (VETERAN, 'veteran'),
        (CIVILIAN, 'civilian'),
    )
    category = models.SmallIntegerField(choices=CATEGORY_TYPES)
    location = models.TextField()
    bio = models.TextField(null=True)
    why_joined = models.TextField(null=True)
    industry = models.ForeignKey('Industry', to_field='id', on_delete=models.PROTECT)
    date_joined = models.DateField(default=datetime.utcnow().replace(tzinfo=utc))

    # vet-only fields
    rank = models.TextField(null=True)
    service_location = models.TextField(null=True)
    service_start_date = models.DateField(null=True)
    service_end_date = models.DateField(null=True)
    HS = 0
    COLLEGE = 1
    GRAD = 2
    EDUCATION_TYPES = (
        (HS, 'high school'),
        (COLLEGE, 'college'),
        (GRAD, 'grad school'),
    )
    education = models.SmallIntegerField(null=True, choices=EDUCATION_TYPES)

    class Meta:
        db_table = 'users'


class Industry(models.Model):
    title = models.TextField()
    code = models.SmallIntegerField()

    class Meta:
        db_table = 'industries'

vetmentor/mentor/forms.py
from __future__ import unicode_literals

from django import forms
from wtforms import Form, TextField, IntegerField, DateField
from wtforms.validators import Required, Optional, AnyOf
from vetmentor.mentor.models import User


class ContactForm(forms.Form):
    recipient = forms.EmailField(required=False, label='To')
    email = forms.EmailField(required=False, label='From')
    subject = forms.CharField(max_length=100)
    message = forms.CharField(required=False, widget=forms.Textarea)
    """
    def clean_message(self):
        message = self.cleaned_data['message']
        num_words = len(message.split())
        if num_words < 4:
            raise forms.ValidationError("Not enough words!")
        return message
    """
        
class SignupForm(Form):
    """
    A new user is signing up.
    """
    name = TextField('name', [Required()])
    email = TextField('email', [Required()])
    password = TextField('password', [Required()])
    birthday = DateField('birthday', [Required()])
    gender = IntegerField('gender', [Required(), AnyOf([User.MALE, User.FEMALE])])
    category = IntegerField('category', [Required(), AnyOf([User.VETERAN, User.CIVILIAN])])
    industry = IntegerField('industry', [Required()])

vetmentor/mentor/views.py
from __future__ import unicode_literals

from django.contrib import auth
from django.core.mail import send_mail      # for contact form
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import View

from vetmentor.mentor.models import User
from vetmentor.mentor import forms


def contact(request):
    # contact form view
    if request.method == 'POST':
        form = forms.ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            send_mail(
                      cd['subject'],
                      cd['message'],
                      cd.get('email', 'noreply@example.com'),
                      [cd.get('recipient', 'downdigitalco@gmail.com')],
                      )
            return HttpResponseRedirect('/contact/thanks/')
    else:
        form = forms.ContactForm(
                           initial={'subject': 'Will you be my mentor?'}
                           )
    return render(request, 'contact_form.html', {'form': form})

def thanks(request):
    return HttpResponse('Thanks for contacting us.')

class LandingView(View):
    """
    Landing page.
    """
    http_method_names = ['get', 'post']

    def get(self, request, *args, **kwargs):
        """
        Show the landing page.
        """
        return render(request, 'landing.html')

class SignupView(View):
    """
    Sign up pages.
    """
    http_method_names = ['post']

    def post(self, request, *args, **kwargs):
        """
        Create a user's account.
        """
        form = forms.SignupForm(request.POST)
        user = User(name=form.name.data,
                    email=form.email.data,
                    birthday=form.birthday.data,
                    gender=form.gender.data,
                    category=form.category.data,
                    industry_id=form.industry.data)
        user.set_password(form.password.data)
        user.save()

        # mimic auth.authenticate, then login
        backend = auth.get_backends()[0]
        user.backend = '%s.%s' % (backend.__module__, backend.__class__.__name__)
        auth.login(request, user)

        return render(request, 'create_vet_profile.html')

vetmentor/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Vet Mentor | {% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="/site_media/style.css" type="text/css" />
</head>
<body>
<div id="header">
        <a href="/"><h1 id="logo">Vet Mentor</h1></a>
    <ul id="nav">
        {% block links %}{% endblock %}
        <li><a href="/">About</a></li>
        <li><a href="/">Browse</a></li>
        {% if user.is_authenticated %}
            <li><a href="/user/{{ user.username }}">{{user.username}}'s
                Profile</a></li>
            <li><a href="/">Logout</a></li>
        {% else %}
            <li><a href="/">Login</a></li>
            <li><a href="/">Sign Up</a></li>
            <li>
                <form action="" method="get"
                    style="vertical-align: bottom; margin: 11% 0;">
                    <input type="text" name="q" placeholder="Find People">
                </form>
            </li>
        {% endif %}
    </ul>
    
</div>
    <h1>{% block head %}{% endblock %}</h1>
    {% block content %}{% endblock %}
</body>
</html>

vetmentor/templates/contact_form.html
<html>
    <head>
        <title>Contact Form</title>
        
        <style type="text/css">
            .field {
                vertical-align: text-top;
            }
            ul.errorlist {
                margin: 0;
                padding: 0;
            }
            .errorlist li {
                background-color: red;
                color: white;
                display: block;
                font-size: 10px;
                margin: 0 0 3px;
                padding: 4px 5px;
            }
            </style>
    </head>
    <body>
        <h1>Contact Form</h1>
        
        {% if form.errors %}
        <p style="color: red;">
        Please correct the error{{ form.errors|pluralize }} below.
        </p>
        {% endif %}
        
        <form action="" method="post"> {% csrf_token %}
            <div class="field">
                {{ form.recipient.errors }}
                <label for="id_recipient">To:</label>
                {{ form.recipient }}
            </div>
            <div class="field">
                {{ form.email.errors }}
                <label for="id_email">From:</label>
                {{ form.email }}
            </div>
            <div class="field">
                {{ form.subject.errors }}
                <label for="id_subject">Subject:</label>
                {{ form.subject }}
            </div>
            <div class="field{% if form.message.errors %} errors{% endif %}">
                {% if form.message.errors %}
                <ul class="errorlist">
                    {% for error in form.message.errors %}
                    <li ><strong>{{ error }}</strong></li>
                    {% endfor %}
                </ul>
                {% endif %}
                <label for="id_message">Message:</label>
                {{ form.message }}
            </div>
            <input type="submit" value="Submit">
                </form>
    </body>
</html>

vetmentor/templates/landing.html
{% extends "base.html" %}
{% block title %}One-on-One Guidance{% endblock %}
{% block head %}{% endblock %}

{% block content %}
    <div style="margin: 20% auto; width: 500px; 
        vertical-align: middle; border: 1px dotted black;">
        <form action="" method="get"
            style="text-align: center; vertical-align: middle;">
            <h3>Peer to peer guidance for all your needs adapting
            from military to civilian life.</h3>
            I'm searching for a 
            <a href="/" class="mentor">Mentor</a> |
            <a href="/" class="mentee">Mentee</a>
            near
            <input type="text" name="q" placeholder="New York, NY">
            <input type="submit" value="Go"><br />
            <a href="/" class="nopref">I'd prefer to talk to anyone.</a>
        </form>
    </div>
{% endblock %}